version: '3.8'

services:
  my-rails-app:
    build:
      context: mcmuralishclint/my-rails-app:latest
      args:
        RUBY_VERSION: 3.2.2
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
