version: '3.3'

services:
  my-rails-app:
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    depends_on:
      - mongo
    image: mcmuralishclint/my-rails-app:latest
  mongo:
    image: mongo
    ports:
      - "27017:27017"
