version: '3.3'

services:
  my-rails-app:
    image: mcmuralishclint/my-rails-app:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: development
      RAILS_HOST: 0.0.0.0
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
