development:
  clients:
    default:
      database: procure
      hosts:
        - localhost:27017
      username: root
      password: root
test:
  clients:
    default:
      database: procure
      hosts:
        - localhost:27017
      username: root
      password: root
