development:
  clients:
    default:
      database: procure
      hosts:
        - mongo:27017

test:
  clients:
    default:
      database: procure
      hosts:
        - mongo:27017

production:
  clients:
    default:
      database: procure
      hosts:
        - mongo:27017