name: "Ruby on Rails CI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      MINIMUM_COVERAGE: 75

    steps:
      - name: Run RuboCop with Auto-Correction
        run: |
          bundle exec rubocop --auto-correct || true

      - name: Run RuboCop to check for remaining offenses
        run: |
          bundle exec rubocop --format simple --fail-level autocorrect -o offenses.txt || true
          offenses_detected=$?
          if [ $offenses_detected -eq 0 ]; then
            echo "RuboCop: All offenses corrected."
          else
            echo "RuboCop: Some offenses detected."
            cat offenses.txt  # Display the detected offenses
          fi

      - name: Check Coverage
        run: |
          # Remaining steps for coverage check...
