name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      MONGODB_VERSION: '4.4'
      MONGODB_URL: 'mongodb://127.0.0.1:27017/raw_data'
    services:
      mongodb:
        image: 'mongo:${{ env.MONGODB_VERSION }}'
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Make bin/bundle executable
        run: chmod +x bin/bundle
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Set up database schema
        run: bundle exec rails db:migrate
      - name: Run RSpec tests
        run: bundle exec rspec